
import { Tier, Member, Reward, DashboardData, Promotion, TierRule, Event, Notification, Product, Transaction, ContentUsage } from './types';

export const TIER_DATA: Record<Tier, TierRule> = {
  [Tier.Normal]: { colorClass: 'bg-tier-normal', hex: '#a0aec0', nextRetail: 20000000, nextWholesale: 100000000, benefits: ['Welcome Gift'] },
  [Tier.Gold]: { colorClass: 'bg-tier-gold', hex: '#d69e2e', nextRetail: 40000000, nextWholesale: 300000000, benefits: ['Birthday Points', 'Personalized Offers'] },
  [Tier.Platinum]: { colorClass: 'bg-tier-platinum text-black', hex: '#d1d5db', nextRetail: 70000000, nextWholesale: 500000000, benefits: ['Anniversary Points', 'Event Invitations'] },
  [Tier.Diamond]: { colorClass: 'bg-tier-diamond text-black', hex: '#b4e1fa', nextRetail: Infinity, nextWholesale: Infinity, benefits: ['Priority Service', 'Exclusive Events'] }
};

export const MOCK_MEMBERS: Member[] = [
  { id: 'MEM001', name: 'Aung Aung', email: 'aung.aung@example.com', phone: '09123456789', nrc: '12/OUKAMA(N)123456', address: 'Yangon, Myanmar', tier: Tier.Platinum, points: 15000, retailSpend: 45000000, wholesaleSpend: 0, joinDate: '2023-01-15', lastVisitDate: '2024-07-10', expirationDate: '2025-01-15', visitFrequency: 25, isBirthday: false, loginCount: 120, lastLogin: '2024-07-16T10:00:00Z' },
  { id: 'MEM002', name: 'Su Su', email: 'su.su@example.com', phone: '09987654321', nrc: '9/BAMANA(N)654321', address: '123 Oak Street, Mandalay, Myanmar', tier: Tier.Gold, points: 7500, retailSpend: 21000000, wholesaleSpend: 0, joinDate: '2023-05-20', lastVisitDate: '2024-06-25', expirationDate: '2025-05-20', visitFrequency: 12, isBirthday: true, loginCount: 85, lastLogin: '2024-07-15T14:30:00Z' },
  { id: 'MEM003', name: 'Kyaw Kyaw (Wholesale)', email: 'kyaw.kyaw@example.com', phone: '09111222333', nrc: '14/PAPANA(N)112233', address: 'Nay Pyi Taw, Myanmar', tier: Tier.Diamond, points: 50000, retailSpend: 0, wholesaleSpend: 550000000, joinDate: '2022-11-01', lastVisitDate: '2024-07-15', expirationDate: '2025-11-01', visitFrequency: 40, isBirthday: false, loginCount: 250, lastLogin: '2024-07-16T09:00:00Z' },
  { id: 'MEM004', name: 'Hla Hla', email: 'hla.hla@example.com', phone: '09444555666', nrc: '7/YANGONA(N)445566', address: 'Bago, Myanmar', tier: Tier.Normal, points: 800, retailSpend: 8000000, wholesaleSpend: 0, joinDate: '2024-02-10', lastVisitDate: '2024-02-11', expirationDate: '2025-02-10', visitFrequency: 5, isBirthday: false, loginCount: 15, lastLogin: '2024-07-10T11:00:00Z' },
  { id: 'MEM005', name: 'Mya Mya', email: 'mya.mya@example.com', phone: '09777888999', nrc: '5/LASHIO(N)778899', address: 'Lashio, Myanmar', tier: Tier.Gold, points: 9200, retailSpend: 38000000, wholesaleSpend: 0, joinDate: '2023-08-08', lastVisitDate: '2023-11-01', expirationDate: '2024-08-15', visitFrequency: 18, isBirthday: false, loginCount: 40, lastLogin: '2024-07-01T18:00:00Z' },
];

export const MOCK_REWARDS: Reward[] = [
  { id: 'REW01', name: '10,000 MMK Voucher', type: 'Voucher', pointsCost: 1000, imageUrl: 'https://picsum.photos/id/1015/300/200', stock: 100 },
  { id: 'REW02', name: 'Premium Coffee Mug', type: 'Product', pointsCost: 2500, imageUrl: 'https://picsum.photos/id/1025/300/200', stock: 50 },
  { id: 'REW03', name: 'Seasonal Discount 5%', type: 'Seasonal', pointsCost: 500, imageUrl: 'https://picsum.photos/id/103/300/200', stock: 200 },
  { id: 'REW04', name: 'Bluetooth Speaker', type: 'Product', pointsCost: 8000, imageUrl: 'https://picsum.photos/id/1062/300/200', stock: 25 },
  { id: 'REW05', name: 'Movie Ticket for Two', type: 'Voucher', pointsCost: 4000, imageUrl: 'https://picsum.photos/id/1078/300/200', stock: 75 },
];

export const MOCK_PROMOTIONS: Promotion[] = [
  { id: 'PROMO01', name: 'Weekend Double Points', description: 'Earn 2x points on all purchases this Saturday & Sunday!', type: 'Double Points', startDate: '2024-07-01', endDate: '2024-12-31' },
  { id: 'PROMO02', name: 'New Year 10% Discount', description: 'Get 10% off on all items.', type: 'Discount', startDate: '2025-01-01', endDate: '2025-01-07' },
  { id: 'PROMO03', name: 'Summer Free Gift', description: 'Receive a free gift with any purchase over 50,000 MMK.', type: 'Gift', startDate: '2024-05-01', endDate: '2024-06-30' },
  { id: 'PROMO04', name: 'Anniversary Special', description: 'Special offers for our anniversary month.', type: 'Discount', startDate: '2024-08-01', endDate: '2024-08-31' },
];

export const MOCK_EVENTS: Event[] = [
    { id: 'EVT001', name: 'Diamond Tier Gala Dinner', description: 'An exclusive dinner for our most valued members.', date: '2024-09-15', location: 'Luxe Hotel Ballroom', targetTiers: [Tier.Diamond] },
    { id: 'EVT002', name: 'Platinum & Gold Workshop', description: 'A workshop on new product arrivals.', date: '2024-10-05', location: 'Yangon Showroom', targetTiers: [Tier.Platinum, Tier.Gold] },
    { id: 'EVT003', name: 'All-Member Year-End Party', description: 'Celebrate the end of the year with us!', date: '2024-12-20', location: 'Central Hall', targetTiers: [Tier.Normal, Tier.Gold, Tier.Platinum, Tier.Diamond] },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
    { id: 'NOTIF01', title: 'New Store Opening!', message: 'Join us for the grand opening of our Mandalay branch on August 1st.', sentDate: '2024-07-15', targetTiers: 'all' },
    { id: 'NOTIF02', title: 'Exclusive Preview', message: 'Diamond members are invited for an exclusive preview of our new collection.', sentDate: '2024-07-10', targetTiers: [Tier.Diamond] },
];

export const MOCK_PRODUCTS: Product[] = [
  { id: 'PROD01', name: 'Luxe Branded Tote Bag', description: 'A stylish and durable tote bag for everyday use.', price: 25000, discountPrice: 19000, imageUrls: ['https://picsum.photos/id/102/600/400', 'https://picsum.photos/id/103/600/400', 'https://picsum.photos/id/104/600/400'], stock: 150 },
  { id: 'PROD02', name: 'Insulated Travel Flask', description: 'Keeps your drinks hot or cold for hours.', price: 45000, imageUrls: ['https://picsum.photos/id/225/600/400', 'https://picsum.photos/id/237/600/400', 'https://picsum.photos/id/227/600/400'], stock: 80 },
  { id: 'PROD03', name: 'Silk Scarf', description: 'A beautiful 100% silk scarf with a unique design.', price: 60000, discountPrice: 49000, imageUrls: ['https://picsum.photos/id/431/600/400', 'https://picsum.photos/id/432/600/400', 'https://picsum.photos/id/433/600/400'], stock: 60 },
  { id: 'PROD04', name: 'Leather Notebook Set', description: 'A premium notebook and pen set for your thoughts.', price: 35000, imageUrls: ['https://picsum.photos/id/535/600/400', 'https://picsum.photos/id/536/600/400', 'https://picsum.photos/id/537/600/400'], stock: 120 },
];

export const MOCK_TRANSACTIONS: Transaction[] = [
  { id: 'TRN001', memberId: 'MEM001', memberName: 'Aung Aung', memberTier: Tier.Platinum, amount: 50000, date: '2024-07-15', status: 'Success', description: 'Annual Membership Fee' },
  { id: 'TRN002', memberId: 'MEM002', memberName: 'Su Su', memberTier: Tier.Gold, amount: 30000, date: '2024-07-14', status: 'Success', description: 'Product Purchase' },
  { id: 'TRN003', memberId: 'MEM004', memberName: 'Hla Hla', memberTier: Tier.Normal, amount: 10000, date: '2024-07-13', status: 'Failed', description: 'Membership Upgrade' },
  { id: 'TRN004', memberId: 'MEM003', memberName: 'Kyaw Kyaw (Wholesale)', memberTier: Tier.Diamond, amount: 100000, date: '2024-07-12', status: 'Success', description: 'Bulk Purchase Credit' },
  { id: 'TRN005', memberId: 'MEM005', memberName: 'Mya Mya', memberTier: Tier.Gold, amount: 30000, date: '2024-06-20', status: 'Success', description: 'Product Purchase' },
  { id: 'TRN006', memberId: 'MEM001', memberName: 'Aung Aung', memberTier: Tier.Platinum, amount: 15000, date: '2024-06-18', status: 'Success', description: 'Event Ticket' },
  { id: 'TRN007', memberId: 'MEM002', memberName: 'Su Su', memberTier: Tier.Gold, amount: 30000, date: '2024-06-05', status: 'Failed', description: 'Product Purchase' },
  { id: 'TRN008', memberId: 'MEM004', memberName: 'Hla Hla', memberTier: Tier.Normal, amount: 5000, date: '2024-05-30', status: 'Success', description: 'Voucher Purchase' },
  { id: 'TRN009', memberId: 'MEM003', memberName: 'Kyaw Kyaw (Wholesale)', memberTier: Tier.Diamond, amount: 250000, date: '2024-05-15', status: 'Success', description: 'Wholesale Order #112' },
  { id: 'TRN010', memberId: 'MEM001', memberName: 'Aung Aung', memberTier: Tier.Platinum, amount: 5000, date: '2024-07-16', status: 'Success', description: 'Coffee Shop Purchase'},
];

export const MOCK_CONTENT_USAGE: ContentUsage[] = [
    { id: 'CONT01', name: 'Weekend Double Points Promotion Details', type: 'Promotion', views: 5201 },
    { id: 'CONT02', name: 'Diamond Tier Gala Dinner Event Page', type: 'Article', views: 1250 },
    { id: 'CONT03', name: 'How to Redeem Points Video', type: 'Video', views: 980 },
    { id: 'CONT04', name: 'New Product Arrival: Luxe Branded Tote Bag', type: 'Article', views: 850 },
    { id: 'CONT05', name: 'Summer Free Gift Promotion', type: 'Promotion', views: 730 },
];

export const MOCK_DASHBOARD_DATA: DashboardData = {
  totalMembers: 1254,
  activePromotions: 5,
  totalPointsRedeemed: 1245000,
  tierDistribution: [
    { name: Tier.Normal, value: 600 },
    { name: Tier.Gold, value: 400 },
    { name: Tier.Platinum, value: 200 },
    { name: Tier.Diamond, value: 54 },
  ],
  salesVsRedemption: [
    { month: 'Jan', sales: 4000, redemptions: 2400 },
    { month: 'Feb', sales: 3000, redemptions: 1398 },
    { month: 'Mar', sales: 2000, redemptions: 9800 },
    { month: 'Apr', sales: 2780, redemptions: 3908 },
    { month: 'May', sales: 1890, redemptions: 4800 },
    { month: 'Jun', sales: 2390, redemptions: 3800 },
  ],
  mostRedeemedItems: [
    { name: '10,000 MMK Voucher', count: 450 },
    { name: 'Premium Coffee Mug', count: 210 },
    { name: 'Movie Ticket for Two', count: 150 },
  ],
  pointsUsageTrends: [
      { date: '2024-01-01', points: 200000 },
      { date: '2024-02-01', points: 180000 },
      { date: '2024-03-01', points: 220000 },
      { date: '2024-04-01', points: 250000 },
      { date: '2024-05-01', points: 210000 },
      { date: '2024-06-01', points: 280000 },
  ]
};

export const translations = {
  en: {
    login: "Login",
    phoneEmail: "Phone or Email",
    password: "Password",
    dashboard: "Dashboard",
    members: "Members",
    rewards: "Rewards",
    promotions: "Promotions",
    analytics: "Analytics",
    events: "Events",
    tierRules: "Tier Rules",
    notifications: "Notifications",
    profile: "Profile",
    logout: "Logout",
    totalMembers: "Total Members",
    activePromotions: "Active Promotions",
    pointsRedeemed: "Points Redeemed",
    salesVsRedemption: "Sales vs. Redemption",
    customerTiers: "Customer Tier Distribution",
    memberList: "Member List",
    searchMember: "Search by name or phone...",
    name: "Name",
    tier: "Tier",
    points: "Points",
    joinDate: "Join Date",
    actions: "Actions",
    viewDetails: "View Details",
    pointShop: "Point Shop",
    redeem: "Redeem",
    myProfile: "My Profile",
    tierProgress: "Tier Progress",
    nextTier: "to next tier",
    currentSpend: "Current Spend (Retail)",
    benefits: "Benefits",
    history: "History",
    purchaseHistory: "Purchase History",
    redemptionHistory: "Redemption History",
    birthdayTitle: "Happy Birthday!",
    birthdayMessage: "We've gifted you 500 bonus points to celebrate your special day!",
    welcome: "Welcome",
    loginPrompt: "Log in to your account",
    myanmar: "Myanmar",
    english: "English",
    personalInformation: "Personal Information",
    emailAddress: "Email Address",
    phoneNumber: "Phone Number",
    nrc: "NRC",
    address: "Address",
    myQRCode: "My QR Code",
    transactionHistory: "History",
    settings: "Settings",
    ecommerce: "Ecommerce",
    store: "Store",
    price: "Price",
    addToCart: "Add to Cart",
    memberReports: "Member Reports",
    memberListReport: "Full Member List",
    newMemberReport: "New Members",
    expirationReport: "Expiring Memberships",
    statusReport: "Active vs. Inactive",
    tierReport: "Members by Tier",
    generateReport: "Generate Report",
    exportExcel: "Export to Excel",
    exportPdf: "Export to PDF",
    allMembers: "All Members",
    newMembersByDate: "New Members by Date Range",
    expiringSoon: "Memberships Expiring in 30 Days",
    memberStatus: "Member Status Overview",
    memberTierDistribution: "Member Tier Distribution",
    active: "Active",
    inactive: "Inactive",
    startDate: "Start Date",
    endDate: "End Date",
    lastVisit: "Last Visit",
    expiresOn: "Expires On",
    memberCount: "Member Count",
    financialReports: "Financial Reports",
    salesRevenueReport: "Sales/Revenue Report",
    revenueByPlanReport: "Revenue by Plan",
    transactionReport: "Transaction Report",
    failedPaymentReport: "Failed Payments",
    totalRevenue: "Total Revenue",
    totalTransactions: "Total Transactions",
    revenue: "Revenue",
    status: "Status",
    amount: "Amount",
    description: "Description",
    successful: "Successful",
    failed: "Failed",
    engagementReports: "Engagement & Activity Reports",
    loginHistoryReport: "Member Login History",
    topActiveMembersReport: "Top Active Members",
    contentUsageReport: "Content/Feature Usage",
    loginCount: "Login Count",
    lastLogin: "Last Login",
    contentType: "Content Type",
    views: "Views",
    menu: "Menu",
  },
  my: {
    login: "ဝင်ရောက်ရန်",
    phoneEmail: "ဖုန်းနံပါတ် သို့မဟုတ် အီးမေးလ်",
    password: "စကားဝှက်",
    dashboard: "ဒိုင်ခွက်",
    members: "အသင်းဝင်များ",
    rewards: "ဆုလာဘ်များ",
    promotions: "ပရိုမိုးရှင်းများ",
    analytics: "ခွဲခြမ်းစိတ်ဖြာချက်",
    events: "အစီအစဉ်များ",
    tierRules: "အဆင့် စည်းမျဉ်းများ",
    notifications: "အသိပေးချက်များ",
    profile: "ကိုယ်ရေးအကျဉ်း",
    logout: "ထွက်ရန်",
    totalMembers: "စုစုပေါင်းအသင်းဝင်",
    activePromotions: "အသက်ဝင်သော ပရိုမိုးရှင်းများ",
    pointsRedeemed: "ရွေးယူထားသော ပွိုင့်များ",
    salesVsRedemption: "အရောင်းနှင့် ရွေးယူမှု",
    customerTiers: "အသင်းဝင် အဆင့်ခွဲဝေမှု",
    memberList: "အသင်းဝင်စာရင်း",
    searchMember: "အမည် သို့မဟုတ် ဖုန်းဖြင့်ရှာပါ...",
    name: "အမည်",
    tier: "အဆင့်",
    points: "ပွိုင့်",
    joinDate: "ဝင်ရောက်သည့်ရက်",
    actions: "လုပ်ဆောင်ချက်များ",
    viewDetails: "အသေးစိတ်ကြည့်ရန်",
    pointShop: "ပွိုင့်ဖြင့် လဲလှယ်ရန်",
    redeem: "လဲလှယ်ရန်",
    myProfile: "ကျွန်ုပ်၏ ပရိုဖိုင်",
    tierProgress: "အဆင့်တိုးတက်မှု",
    nextTier: "နောက်အဆင့်သို့",
    currentSpend: "လက်ရှိအသုံးစရိတ် (လက်လီ)",
    benefits: "အကျိုးကျေးဇူးများ",
    history: "မှတ်တမ်း",
    purchaseHistory: "ဝယ်ယူမှုမှတ်တမ်း",
    redemptionHistory: "လဲလှယ်မှုမှတ်တမ်း",
    birthdayTitle: "မွေးနေ့",
    birthdayMessage: "သင့်မွေးနေ့အတွက် အပိုဆု 500 ပွိုင့် လက်ဆောင်ပေးလိုက်ပါတယ်!",
    welcome: "ကြိုဆိုပါတယ်",
    loginPrompt: "သင့်အကောင့်သို့ ဝင်ရောက်ပါ။",
    myanmar: "မြန်မာ",
    english: "အင်္ဂလိပ်",
    personalInformation: "ကိုယ်ရေးကိုယ်တာအချက်အလက်",
    emailAddress: "အီးမေးလ်လိပ်စာ",
    phoneNumber: "ဖုန်းနံပါတ်",
    nrc: "နိုင်ငံသားစိစစ်ရေးကတ်အမှတ်",
    address: "လိပ်စာ",
    myQRCode: "ကျွန်ုပ်၏ QR Code",
    transactionHistory: "မှတ်တမ်း",
    settings: "ဆက်တင်များ",
    ecommerce: "အီလက်ထရွန်နစ် ကုန်သွယ်မှု",
    store: "ဆိုင်",
    price: "ဈေးနှုန်း",
    addToCart: "စျေးဝယ်ခြင်းထဲသို့ထည့်ပါ",
    memberReports: "Member Report များ",
    memberListReport: "Member စာရင်း အပြည့်အစုံ",
    newMemberReport: "Member အသစ်များ",
    expirationReport: "သက်တမ်းကုန်ဆုံးမည့် Member များ",
    statusReport: "Active နှင့် Inactive Member",
    tierReport: "အဆင့်အလိုက် Member များ",
    generateReport: "Report ထုတ်ရန်",
    exportExcel: "Excel သို့ Export လုပ်ရန်",
    exportPdf: "PDF သို့ Export လုပ်ရန်",
    allMembers: "Member အားလုံး",
    newMembersByDate: "ရက်အပိုင်းအခြားအလိုက် Member အသစ်များ",
    expiringSoon: "ရက် ၃၀ အတွင်း သက်တမ်းကုန်ဆုံးမည့် Member များ",
    memberStatus: "Member အခြေအနေ ခြုံငုံကြည့်ရှုခြင်း",
    memberTierDistribution: "Member အဆင့်အလိုက် ဖြန့်ဝေမှု",
    active: "Active",
    inactive: "Inactive",
    startDate: "စတင်သည့်ရက်",
    endDate: "ပြီးဆုံးသည့်ရက်",
    lastVisit: "နောက်ဆုံး လာရောက်သည့်ရက်",
    expiresOn: "သက်တမ်းကုန်ဆုံးရက်",
    memberCount: "Member အရေအတွက်",
    financialReports: "ငွေကြေးဆိုင်ရာ Report များ",
    salesRevenueReport: "အရောင်း/ဝင်ငွေ Report",
    revenueByPlanReport: "အစီအစဉ်အလိုက် ဝင်ငွေ",
    transactionReport: "ငွေပေးချေမှုမှတ်တမ်း",
    failedPaymentReport: "မအောင်မြင်သော ငွေပေးချေမှုများ",
    totalRevenue: "စုစုပေါင်းဝင်ငွေ",
    totalTransactions: "စုစုပေါင်း ငွေလွှဲမှုများ",
    revenue: "ဝင်ငွေ",
    status: "အခြေအနေ",
    amount: "ပမာဏ",
    description: "အကြောင်းအရာ",
    successful: "အောင်မြင်သည်",
    failed: "မအောင်မြင်ပါ",
    engagementReports: "အသုံးပြုမှုဆိုင်ရာ Report များ",
    loginHistoryReport: "Member Login မှတ်တမ်း",
    topActiveMembersReport: "အသုံးအများဆုံး Member များ",
    contentUsageReport: "Content အသုံးပြုမှု",
    loginCount: "Login အရေအတွက်",
    lastLogin: "နောက်ဆုံး Login",
    contentType: "Content အမျိုးအစား",
    views: "ကြည့်ရှုမှု",
    menu: "မီနူး",
  },
};
