import { Tier, Member, Reward, DashboardData } from './types';

export const TIER_DATA: Record<Tier, { colorClass: string; hex: string; nextRetail: number; nextWholesale: number; benefits: string[] }> = {
  [Tier.Normal]: { colorClass: 'bg-tier-normal', hex: '#a0aec0', nextRetail: 20000000, nextWholesale: 100000000, benefits: ['Welcome Gift'] },
  [Tier.Gold]: { colorClass: 'bg-tier-gold', hex: '#d69e2e', nextRetail: 40000000, nextWholesale: 300000000, benefits: ['Birthday Points', 'Personalized Offers'] },
  [Tier.Platinum]: { colorClass: 'bg-tier-platinum text-black', hex: '#d1d5db', nextRetail: 70000000, nextWholesale: 500000000, benefits: ['Anniversary Points', 'Event Invitations'] },
  [Tier.Diamond]: { colorClass: 'bg-tier-diamond text-black', hex: '#b4e1fa', nextRetail: Infinity, nextWholesale: Infinity, benefits: ['Priority Service', 'Exclusive Events'] }
};

export const MOCK_MEMBERS: Member[] = [
  { id: 'MEM001', name: 'Aung Aung', email: 'aung.aung@example.com', phone: '09123456789', nrc: '12/OUKAMA(N)123456', address: 'Yangon, Myanmar', tier: Tier.Platinum, points: 15000, retailSpend: 45000000, wholesaleSpend: 0, joinDate: '2023-01-15', visitFrequency: 25, isBirthday: false },
  { id: 'MEM002', name: 'Su Su', email: 'su.su@example.com', phone: '09987654321', nrc: '9/BAMANA(N)654321', address: '123 Oak Street, Mandalay, Myanmar', tier: Tier.Gold, points: 7500, retailSpend: 21000000, wholesaleSpend: 0, joinDate: '2023-05-20', visitFrequency: 12, isBirthday: true },
  { id: 'MEM003', name: 'Kyaw Kyaw (Wholesale)', email: 'kyaw.kyaw@example.com', phone: '09111222333', nrc: '14/PAPANA(N)112233', address: 'Nay Pyi Taw, Myanmar', tier: Tier.Diamond, points: 50000, retailSpend: 0, wholesaleSpend: 550000000, joinDate: '2022-11-01', visitFrequency: 40, isBirthday: false },
  { id: 'MEM004', name: 'Hla Hla', email: 'hla.hla@example.com', phone: '09444555666', nrc: '7/YANGONA(N)445566', address: 'Bago, Myanmar', tier: Tier.Normal, points: 800, retailSpend: 8000000, wholesaleSpend: 0, joinDate: '2024-02-10', visitFrequency: 5, isBirthday: false },
  { id: 'MEM005', name: 'Mya Mya', email: 'mya.mya@example.com', phone: '09777888999', nrc: '5/LASHIO(N)778899', address: 'Lashio, Myanmar', tier: Tier.Gold, points: 9200, retailSpend: 38000000, wholesaleSpend: 0, joinDate: '2023-08-08', visitFrequency: 18, isBirthday: false },
];

export const MOCK_REWARDS: Reward[] = [
  { id: 'REW01', name: '10,000 MMK Voucher', type: 'Voucher', pointsCost: 1000, imageUrl: 'https://picsum.photos/id/1015/300/200', stock: 100 },
  { id: 'REW02', name: 'Premium Coffee Mug', type: 'Product', pointsCost: 2500, imageUrl: 'https://picsum.photos/id/1025/300/200', stock: 50 },
  { id: 'REW03', name: 'Seasonal Discount 5%', type: 'Seasonal', pointsCost: 500, imageUrl: 'https://picsum.photos/id/103/300/200', stock: 200 },
  { id: 'REW04', name: 'Bluetooth Speaker', type: 'Product', pointsCost: 8000, imageUrl: 'https://picsum.photos/id/1062/300/200', stock: 25 },
  { id: 'REW05', name: 'Movie Ticket for Two', type: 'Voucher', pointsCost: 4000, imageUrl: 'https://picsum.photos/id/1078/300/200', stock: 75 },
];

export const MOCK_DASHBOARD_DATA: DashboardData = {
  totalMembers: 1254,
  activePromotions: 5,
  totalPointsRedeemed: 1245000,
  tierDistribution: [
    { name: Tier.Normal, value: 600 },
    { name: Tier.Gold, value: 400 },
    { name: Tier.Platinum, value: 200 },
    { name: Tier.Diamond, value: 54 },
  ],
  salesVsRedemption: [
    { month: 'Jan', sales: 4000, redemptions: 2400 },
    { month: 'Feb', sales: 3000, redemptions: 1398 },
    { month: 'Mar', sales: 2000, redemptions: 9800 },
    { month: 'Apr', sales: 2780, redemptions: 3908 },
    { month: 'May', sales: 1890, redemptions: 4800 },
    { month: 'Jun', sales: 2390, redemptions: 3800 },
  ],
  mostRedeemedItems: [
    { name: '10,000 MMK Voucher', count: 450 },
    { name: 'Premium Coffee Mug', count: 210 },
    { name: 'Movie Ticket for Two', count: 150 },
  ],
  pointsUsageTrends: [
      { date: '2024-01-01', points: 200000 },
      { date: '2024-02-01', points: 180000 },
      { date: '2024-03-01', points: 220000 },
      { date: '2024-04-01', points: 250000 },
      { date: '2024-05-01', points: 210000 },
      { date: '2024-06-01', points: 280000 },
  ]
};

export const translations = {
  en: {
    login: "Login",
    phoneEmail: "Phone or Email",
    password: "Password",
    dashboard: "Dashboard",
    members: "Members",
    rewards: "Rewards",
    profile: "Profile",
    logout: "Logout",
    totalMembers: "Total Members",
    activePromotions: "Active Promotions",
    pointsRedeemed: "Points Redeemed",
    salesVsRedemption: "Sales vs. Redemption",
    customerTiers: "Customer Tier Distribution",
    memberList: "Member List",
    searchMember: "Search by name or phone...",
    name: "Name",
    tier: "Tier",
    points: "Points",
    joinDate: "Join Date",
    actions: "Actions",
    viewDetails: "View Details",
    pointShop: "Point Shop",
    redeem: "Redeem",
    myProfile: "My Profile",
    tierProgress: "Tier Progress",
    nextTier: "to next tier",
    currentSpend: "Current Spend (Retail)",
    benefits: "Benefits",
    history: "History",
    purchaseHistory: "Purchase History",
    redemptionHistory: "Redemption History",
    notifications: "Notifications",
    birthdayTitle: "Happy Birthday!",
    birthdayMessage: "We've gifted you 500 bonus points to celebrate your special day!",
    welcome: "Welcome",
    loginPrompt: "Log in to your account",
    myanmar: "Myanmar",
    english: "English",
    personalInformation: "Personal Information",
    emailAddress: "Email Address",
    phoneNumber: "Phone Number",
    nrc: "NRC",
    address: "Address",
  },
  my: {
    login: "ဝင်ရောက်ရန်",
    phoneEmail: "ဖုန်းနံပါတ် သို့မဟုတ် အီးမေးလ်",
    password: "စကားဝှက်",
    dashboard: "ဒိုင်ခွက်",
    members: "အသင်းဝင်များ",
    rewards: "ဆုလာဘ်များ",
    profile: "ကိုယ်ရေးအကျဉ်း",
    logout: "ထွက်ရန်",
    totalMembers: "စုစုပေါင်းအသင်းဝင်",
    activePromotions: "အသက်ဝင်သော ပရိုမိုးရှင်းများ",
    pointsRedeemed: "ရွေးယူထားသော ပွိုင့်များ",
    salesVsRedemption: "အရောင်းနှင့် ရွေးယူမှု",
    customerTiers: "အသင်းဝင် အဆင့်ခွဲဝေမှု",
    memberList: "အသင်းဝင်စာရင်း",
    searchMember: "အမည် သို့မဟုတ် ဖုန်းဖြင့်ရှာပါ...",
    name: "အမည်",
    tier: "အဆင့်",
    points: "ပွိုင့်",
    joinDate: "ဝင်ရောက်သည့်ရက်",
    actions: "လုပ်ဆောင်ချက်များ",
    viewDetails: "အသေးစိတ်ကြည့်ရန်",
    pointShop: "ပွိုင့်ဖြင့် လဲလှယ်ရန်",
    redeem: "လဲလှယ်ရန်",
    myProfile: "ကျွန်ုပ်၏ ပရိုဖိုင်",
    tierProgress: "အဆင့်တိုးတက်မှု",
    nextTier: "နောက်အဆင့်သို့",
    currentSpend: "လက်ရှိအသုံးစရိတ် (လက်လီ)",
    benefits: "အကျိုးကျေးဇူးများ",
    history: "မှတ်တမ်း",
    purchaseHistory: "ဝယ်ယူမှုမှတ်တမ်း",
    redemptionHistory: "လဲလှယ်မှုမှတ်တမ်း",
    notifications: "အသိပေးချက်များ",
    birthdayTitle: "မွေးနေ့ مبارک!",
    birthdayMessage: "သင့်မွေးနေ့အတွက် အပိုဆု 500 ပွိုင့် လက်ဆောင်ပေးလိုက်ပါတယ်!",
    welcome: "ကြိုဆိုပါတယ်",
    loginPrompt: "သင့်အကောင့်သို့ ဝင်ရောက်ပါ။",
    myanmar: "မြန်မာ",
    english: "အင်္ဂလိပ်",
    personalInformation: "ကိုယ်ရေးကိုယ်တာအချက်အလက်",
    emailAddress: "အီးမေးလ်လိပ်စာ",
    phoneNumber: "ဖုန်းနံပါတ်",
    nrc: "နိုင်ငံသားစိစစ်ရေးကတ်အမှတ်",
    address: "လိပ်စာ",
  },
};